# Generated by Django 4.2.6 on 2024-03-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
