# Generated by Django 4.2.6 on 2024-03-14 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_basketitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='api.basket'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
